{% set version = "2.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mitools
  version: {{ version|replace("-", "_") }}

source:
  fn: mitools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/mitools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mitools/mitools_{{ version }}.tar.gz
  sha256: f204f3774e29d79810f579f128de892539518f2cbe6ed237e08c8e7283155d30

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('mitools')"  # [not win]
    - "\"%R%\" -e \"library('mitools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mitools
  license: GPL-2
  summary: Tools to perform analyses and combine results from multiple-imputation datasets.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
