appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: AdzJQy8JsMy/S4763ICXssANg3S5kmUScnDVaY64jiVOsMQSSZfS5loECyKVjC7dmUs3E5lQkU+5DTWLNB3nsL76OjUlr6MMIUj3QUcxrB8X70VBKKciOajj13MAH+Dc63zYbE163YD1rd8zN08WRGX+XKeyJ6lTXY6chjX+FnRtu/Gv4ugbXrMJeXyDwzCu8mqYsByw7goRJNDmI3aaQB/eRaBlHqFOzlFYLbIkPRXQq8+EAiU8oBxb0jyAGlMPvar7QGL2lAC23wSwdlbmFgEnFYT667NMuKgJoC97oaddhssIreSlOWnvoft9Cgz6089M0DnuC2NwndDxc91OYM0AHYkG6nA+gzvn74S0HxYOijW9sR+pIt1mmK7NB1pYUrHmoHVmSZhEvmUnTGbB1cRDTNdN4yGhhCCErh0ce0pRF9ZLzwkXxmMb8YgWfn2kTKG8srepmyM+yqN+Iv4NvzcgnIV0a/Sji5EebJqvKHwEIo3pKfXXn8njJ+94NroQ5EHlUFlk5qmzMmgVUlNXUE5QVCdhjzHFhNJvGh99jWZsBlbhcV8WEPcdoTQHYugnPQTTlDPT9rocM/1DwVW5fzsgiiK93upNAnwSnhrnyBmO5z+MGfikwLzzGZ6R85Y6cAFqD1z0/K+14OK2ZxZaa7MZ1p/1EcPaFg+S1FCXk7w=}
bot:
  automerge: true
